### ISSUE TITLE
PointerIndex out of range

### ISSUE THREAD

**Issue by Frange** [yanzm/LoopViewPager#5]
I'm having this issue in Splunk with users but I can't reproduce it with my devices.
This trace is not from my app code so maybe there is something wrong with this library.

This is all the information I'm receiving:

File: PhoneWindow.java:2410

1   java.lang.IllegalArgumentException: pointerIndex out of range
1	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
2	at android.view.MotionEvent.getX(MotionEvent.java:2072)
3	at android.support.v4.view.LoopViewPager.onInterceptTouchEvent(LoopViewPager.java:2102)
4	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)
5	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
6	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
7	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
8	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
9	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
10	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
11	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
12	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
13	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
14	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
15	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
16	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
17	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2410)
18	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1744)
19	at android.app.Activity.dispatchTouchEvent(Activity.java:2805)
20	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2371)
21	at android.view.View.dispatchPointerEvent(View.java:9597)
22	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4234)
23	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4100)
24	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
25	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
26	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
27	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
28	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
29	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
30	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
31	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
32	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
33	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
34	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
35	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5926)
36	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5900)
37	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5861)
38	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6029)
39	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
40	at android.os.MessageQueue.nativePollOnce(Native Method)
41	at android.os.MessageQueue.next(MessageQueue.java:331)
42	at android.os.Looper.loop(Looper.java:218)
43	at android.app.ActivityThread.main(ActivityThread.java:5526)
44	at java.lang.reflect.Method.invoke(Native Method)
45	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
46	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by yanzm** [comment]
I've nothing changed code in onInterceptTouchEvent() from original ViewPager.
So this seems a bug in original ViewPager.
